# Generated by Django 4.1.7 on 2023-04-11 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='moderator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='conference_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
