# Generated by Django 4.1.7 on 2023-03-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.event')),
                ('resource_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.resourceitem')),
            ],
            options={
                'db_table': 'reserved_item',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='reserved_items',
            field=models.ManyToManyField(through='conference.ReservedItem', to='conference.resourceitem'),
        ),
    ]
