# Generated by Django 4.1.7 on 2023-03-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_reserveditem_event_reserved_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.AddField(
            model_name='room',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.event'),
        ),
    ]
