# Generated by Django 4.1.7 on 2023-05-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0002_conference_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='location',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='room',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='moderator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.room'),
        ),
    ]
