# Generated by Django 4.1.7 on 2023-03-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_remove_room_occupied_room_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_items', to='conference.location'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conference.location'),
        ),
    ]
