# Generated by Django 4.1.7 on 2023-05-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0003_remove_conference_moderator_remove_location_occupied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reserved_items',
        ),
        migrations.RemoveField(
            model_name='event',
            name='visitors',
        ),
        migrations.CreateModel(
            name='EventVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.event')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_visitor',
            },
        ),
    ]
