# Generated by Django 4.1.7 on 2023-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_remove_event_reserved_items_remove_event_visitors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='conference',
            name='finished',
            field=models.BooleanField(db_column='finished', default=False),
        ),
    ]
