# Generated by Django 4.1.7 on 2023-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_alter_conference_options_alter_conference_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='finished',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='finished',
            field=models.SmallIntegerField(),
        ),
    ]
